### PR TITLE
Rm table individual catalog update

### PR DESCRIPTION
**Pull request by anthony-nunez**
Changes to Minter96.fits and Clegg92.fits

### CODE REVIEW

**Comment by Cameron-Van-Eck** [comment]
Hi @anthony-nunez:

Thanks for the fixes. The Galactic coordinates look good, and the blank columns now have NaNs. Perhaps too many NaNs -- the string columns have been converted to float columns with NaNs. It's giving me an error message when I try to merge your catalogs in with the others: it doesn't want to merge the columns where one table has floats (NaNs) and the other has strings. E.g.: `TableMergeError: The 'complex_test' columns have incompatible types: ['str32', 'float64']`. Ideally, the blank string columns should just be empty strings.

Do you want to fix this, or shall I? I can fix this if it's becoming tedious. :)

Cheers,
Cameron

**Comment by anthony-nunez** [comment]
Hi Cameron,

Thank you again for pointing this out. I apologize for these errors; I'm still getting used to working with fits files, fits file conversions, and associated libraries.

I have time tomorrow to fix this, but I'm just not too sure exactly where I'm going wrong. If you have the time, could you provide some guidance on how to address this?

I could describe the process I used to create the most recent files if that would be helpful.

Warmly,

Anthony


________________________________

**Comment by Cameron-Van-Eck** [comment]
Hi Anthony:

No problem, FITS stuff can be fussy at the best of times. It's a bit hard to guess where things are going wrong, so some description of your process would be very helpful. Are you not using the RMTable module to handle read/write of the tables? Part of its purpose is to make it easier to handle read/write operations and to preserve the column formats, so if it's not doing that then I should try to fix that.

Regardless of how you're doing it, I think maybe the best place to start is to check the column data types at various points: are they read in wrong, or are they correct after input; are they correct prior to writing out? That can narrow down where the problem occurs. If it helps, the list of expected column formats can be found as the "dtype" keywords in this file: https://github.com/CIRADA-Tools/RMTable/blob/master/rmtable/column_standard_v1.3.json

Hope that helps,
Cameron

**Comment by anthony-nunez** [comment]
Hello Cameron,

Thank you for the help! I was using the RMTable module, but I was converting the individual catalogs to tsvs and editing them with Numbers (MacOS version of excel). Then converting back to fits using .write().

This time, I'm keeping the individual catalogs as fits, reading them as tables, and editing the table. Then I wrote it to fits.

I'm checking the dtypes of the columns and they seem fine, except for the ones labelled "U" in the link you sent. See the attached screenshot for an example of the difference.

Notably, "complex_test" was one of the columns which received an incorrect "nan" last time.

 It seems like this might not be an issue? but I'm not sure.

Please let me know if that seems fine to you, or if you need more information.

Best,
Anthony


________________________________

**Comment by Cameron-Van-Eck** [comment]
Hi Anthony:

The screenshot seems to have not survived the trip through Github -- you could try again but sending via the Github page rather than by email. Was the problem that the "U" columns get converted to "S"-type when read in? I looked at that a little bit after my message yesterday -- this is the astropy fits table reader being a bit quirky, but is otherwise harmless.

If you have a new version of the table that looks OK then please commit it and I'll take a look.

Thanks!
Cameron

**Comment by anthony-nunez** [comment]
Hello,

Yes, it converted to "S" type. If it's harmless, then I'll commit these new files now!
________________________________

**Comment by Cameron-Van-Eck** [comment]
Thanks for the fixes! It looks great now, so I'll merge it in. The new version will go live in the 1.2.0 catalog release, which I'm going to try to do right away today.

**Pull request merged**
